# config/blacklight.yml

# =============================================================================
# Settings not directly related to a specific Rails environment.
# =============================================================================

# Production Solr instance (UVa on-Grounds or via VPN).
_solr_uva_prod:                                                  &SOLR_UVA_PROD
  adapter: solr
  url:     http://junco.lib.virginia.edu:8080/solr/test_core

# Development Solr instance (UVa on-Grounds or via VPN).
_solr_uva_dev:                                                    &SOLR_UVA_DEV
  adapter: solr
  url:     http://junco.lib.virginia.edu:8080/solr/test_core

# Local development fake Solr instance.
_solr_local:                                                        &SOLR_LOCAL
  adapter: solr
  url: <%=
    ENV['SOLR_URL'] ||
    "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/blacklight-core"
  %>

# =============================================================================
# Desktop development configurations (UVa on-Grounds or via VPN)
# =============================================================================

# For the 'production' Rails environment (local).
production:                                                    &SOLR_LOCAL_PROD
  adapter: solr
  url:     http://junco.lib.virginia.edu:8080/solr/test_core

# For the 'development' Rails environment (local).
development:                                                    &SOLR_LOCAL_DEV
  adapter: solr
  url:     http://junco.lib.virginia.edu:8080/solr/test_core

# For the 'test' Rails environment (local).
test:                                                          &SOLR_LOCAL_TEST
  adapter: solr
  url: <%=
         ENV['SOLR_URL'] ||
         "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/blacklight-core"
  %>
